# Generated by Django 2.1.5 on 2020-07-25 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
