# Generated by Django 2.1.5 on 2020-07-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('age', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=64)),
                ('highest_education', models.CharField(max_length=64)),
                ('track', models.CharField(max_length=64)),
                ('describtion', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
