# Generated by Django 2.1.5 on 2020-07-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='level',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
