# Generated by Django 2.1.5 on 2020-07-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='topic',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=models.TextField(max_length=265),
        ),
    ]
