# Generated by Django 2.1.5 on 2020-08-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200828_0442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userscomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=512)),
                ('username', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Usersinfo',
        ),
    ]
