# Generated by Django 2.1.5 on 2020-08-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200828_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscomment',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userscomment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
