# Generated by Django 2.1.5 on 2020-08-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200829_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscomment',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
