# Generated by Django 2.1.5 on 2020-08-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200829_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscomment',
            name='post_id',
            field=models.IntegerField(null=True),
        ),
    ]
