# Generated by Django 2.1.5 on 2020-08-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200829_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userscomment',
            name='id',
        ),
        migrations.AddField(
            model_name='userscomment',
            name='user_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
