# Generated by Django 2.1.5 on 2020-09-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200910_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.AddField(
            model_name='like',
            name='no_of_dislikes',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='like',
            name='no_of_likes',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='like',
            name='post_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
