# Generated by Django 3.1.1 on 2020-09-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200914_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categorey',
            field=models.TextField(default=None),
        ),
    ]
