# Generated by Django 3.1.1 on 2020-10-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20201001_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='year_in_school',
            field=models.CharField(choices=[(1, 'asdasdasd')], default='x', max_length=2),
        ),
    ]
