# Generated by Django 3.1.1 on 2020-10-01 14:42

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20201001_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='year_in_school',
        ),
        migrations.AlterField(
            model_name='post',
            name='categorey',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(2, 'gaming'), (3, 'coding')], default='x', max_length=2),
        ),
    ]
