# Generated by Django 3.1.1 on 2020-10-01 16:39

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_auto_20201001_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categorey',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('gaming', 'gaming'), ('coding', 'coding'), ('testing', 'testing'), ('IOT', 'IOT')], default='x', max_length=10),
        ),
    ]
