# Generated by Django 3.1.1 on 2020-10-01 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_auto_20201001_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoreies',
            old_name='categorey_name',
            new_name='category_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='categorey',
        ),
    ]
