# Generated by Django 3.1.1 on 2020-10-01 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20201001_1842'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoreies',
        ),
    ]
