# Generated by Django 3.1.1 on 2020-10-01 16:49

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_categoreies'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('coding', 'coding')], default='x', max_length=10),
        ),
    ]
