# Generated by Django 3.1.1 on 2020-10-05 13:56

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Coding', 'Coding'), ('ML', 'ML'), ('IOT', 'IOT'), ('Python', 'Python')], default='x', max_length=20),
        ),
    ]
