# Generated by Django 3.1.1 on 2020-10-05 14:10

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_auto_20201005_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cat',
            field=models.ManyToManyField(to='blog.Categoreies'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Coding', 'Coding'), ('ML', 'ML'), ('IOT', 'IOT'), ('Python', 'Python')], default='uncategorized', max_length=20),
        ),
    ]
