# Generated by Django 3.1.1 on 2020-10-05 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_auto_20201005_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
