# Generated by Django 3.1.1 on 2020-10-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_remove_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoreies',
            name='category_name',
            field=models.CharField(default='uncategorized', max_length=200),
        ),
    ]
