# Generated by Django 3.1.1 on 2020-10-05 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_auto_20201005_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cat',
            new_name='category',
        ),
    ]
